#!/usr/bin/env node
/* theme-js.mjs — generates the Drupal theme's js/ from the repo-root js/.
 *
 * Each source file is one IIFE that maps to one Drupal.behaviors entry
 * (docs/animation.md, "Drupal port" table). Rather than fork the files, this
 * wraps each source VERBATIM in an attach() that runs it once per page
 * (once() on <html>; an AJAX context never contains <html>, so re-attaches are
 * no-ops). The behaviour body stays byte-identical to the prototype's, so the
 * static templates remain the reference and the theme can never drift.
 *
 * Two files stay plain IIFEs: velocity-lean (it only defines the shared
 * window.ICON.velocityLean, and consumers declare the library dependency) and
 * hero-loader (it must run in <head>, before anything else — see its header).
 *
 * Prototype-only behaviours (hero, tagline, hero-sphere) are not ported: the
 * pages that use them are outside the system (AGENTS.md).
 *
 * Run via `npm run build:theme`; `npm run verify` checks the output is current.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const src = join(root, "js");
const out = join(root, "drupal/web/themes/custom/icon/js");

/** file basename → Drupal.behaviors key (null = plain IIFE, copied as-is). */
export const BEHAVIOURS = {
  "header": "iconHeader",
  "reveal": "iconReveal",
  "velocity-lean": null,
  "site-footer": "iconFooter",
  "theme-handover": "iconThemeHandover",
  "news": "iconNews",
  "share": "iconShare",
  "subscribe-reveal": "iconSubscribeReveal",
  "work-landing": "iconWorkLanding",
  "work": "iconWork",
  "work-filter": "iconWorkFilter",
  "work-article": "iconWorkArticle",
  "work-scroller": "iconWorkScroller",
  "work-video": "iconWorkVideo",
  "hero-loader": null,
  "home-c": "iconHomeC",
};

export function generate(name, behaviour, source) {
  const banner =
    `/* ${name}.js — GENERATED by scripts/theme-js.mjs from the repo-root js/${name}.js.\n` +
    ` * Do not edit here: edit the source and run \`npm run build:theme\`.\n`;
  if (!behaviour) {
    return banner + ` * Plain IIFE (no behaviour wrapper) — see the generator for why. */\n\n` + source;
  }
  const indented = source.replace(/^(?=.)/gm, "      ");
  return (
    banner +
    ` * The source IIFE runs once per page inside Drupal.behaviors.${behaviour}.attach()\n` +
    ` * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */\n` +
    `((Drupal, once) => {\n` +
    `  Drupal.behaviors.${behaviour} = {\n` +
    `    attach(context) {\n` +
    `      if (!once("${name}", "html", context).length) return;\n\n` +
    indented +
    `\n    },\n  };\n})(Drupal, once);\n`
  );
}

export function build() {
  mkdirSync(out, { recursive: true });
  const files = {};
  for (const [name, behaviour] of Object.entries(BEHAVIOURS)) {
    const source = readFileSync(join(src, `${name}.js`), "utf8");
    files[`${name}.js`] = generate(name, behaviour, source);
  }
  return files;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = build();
  for (const [file, code] of Object.entries(files)) writeFileSync(join(out, file), code);
  console.log(`theme-js: ${Object.keys(files).length} behaviours → drupal/web/themes/custom/icon/js/`);
}
