/* header.js — GENERATED by scripts/theme-js.mjs from the repo-root js/header.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconHeader.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconHeader = {
    attach(context) {
      if (!once("header", "html", context).length) return;

      /* header.js — desktop nav scroll state + mobile menu toggle.
       * Port of the scroll/menu logic in v40-1-icon/components/navigation-bar.tsx.
       * The SERVICES submenu is CSS-driven (hover/focus-within); only the scroll
       * state and the mobile menu need JS.
       *
       * Drupal: becomes Drupal.behaviors.iconHeader attached via `icon/header`. */
      (function () {
        "use strict";

        var nav = document.querySelector("[data-nav]");
        var logo = document.querySelector(".site-logo");
        var mobileHome = document.querySelector("[data-mobile-home]");
        var toggle = document.querySelector("[data-menu-toggle]");
        var menu = document.querySelector("[data-mobile-menu]");
        // The search flip closes the SERVICES drawer before it rolls; the drawer's
        // close is defined inside its own block below and handed up through this.
        var closeSubmenu = function () {};
        // The phone's menu closes the search face with it, the same way.
        var closeSearch = function () {};

        // ---- Scroll state: frosted pill (>10px), then the hero-exit swap at >100px —
        //      the wordmark fades out as the home glyph (pill + mobile button) fades in.
        function onScroll() {
          var y = window.scrollY;
          if (nav) {
            nav.classList.toggle("is-scrolled", y > 10);
            nav.classList.toggle("show-home", y > 100);
          }
          if (mobileHome) mobileHome.classList.toggle("is-visible", y > 100);
          // Logo fade is a one-shot CSS transition triggered HERE (not scroll-scrubbed),
          // at the same point the glyph appears, so the two swap together and the fade
          // always runs to completion. Also drops pointer events once hidden.
          if (logo) logo.classList.toggle("is-faded", y > 100);
        }
        window.addEventListener("scroll", onScroll, { passive: true });
        onScroll();

        // ---- Mobile menu ----
        function isOpen() {
          return menu && menu.classList.contains("is-open");
        }

        function openMenu() {
          if (!menu) return;
          menu.hidden = false;
          window.requestAnimationFrame(function () {
            menu.classList.add("is-open");
          });
          if (toggle) {
            toggle.classList.add("is-open");
            toggle.setAttribute("aria-expanded", "true");
            toggle.setAttribute("aria-label", "Close menu");
          }
          document.body.classList.add("is-menu-open");
        }

        function closeMenu() {
          if (!menu) return;
          menu.classList.remove("is-open");
          if (toggle) {
            toggle.classList.remove("is-open");
            toggle.setAttribute("aria-expanded", "false");
            toggle.setAttribute("aria-label", "Open menu");
          }
          document.body.classList.remove("is-menu-open");
          window.setTimeout(function () {
            if (!isOpen()) menu.hidden = true;
          }, 400);
        }

        if (toggle) {
          toggle.addEventListener("click", function () {
            if (isOpen()) closeMenu();
            else openMenu();
          });
        }

        document.addEventListener("keydown", function (e) {
          if (e.key === "Escape" && isOpen()) closeMenu();
        });

        // Close when a menu link is followed.
        if (menu) {
          menu.addEventListener("click", function (e) {
            if (e.target.closest("a")) closeMenu();
          });
        }

        // ---- The phone's menu (the pill's rest square, below md) ----
        // CSS collapses the pill to the burger without .is-open; this opens it and
        // closes it on a tap outside, a scroll of more than 40px from where it
        // opened, a link followed, Esc, or a resize up to the desktop (user call,
        // 23 Sep 2026: no close button — "tap outside or a link").
        var burger = document.querySelector("[data-nav-burger]");
        var closeMobileNav = function () {};
        if (nav && burger) {
          var mOpenY = 0;
          // The rest square's side: the row's height (the CSS adds the padding),
          // measured — it is the links' line plus their padding at the fitted
          // voice, which no token states — on load, after the fonts, on resize.
          // Set on the HEADER, with the pill's own height, so the wordmark (the
          // pill's sibling) can sit its bubble on the square's centre.
          var mRow = nav.querySelector(".site-nav__row");
          var mPill = nav.querySelector(".site-nav__pill--nav");
          var mHost = nav.closest(".site-header") || nav;
          function mRowH() {
            if (mRow) mHost.style.setProperty("--nav-row-h", mRow.offsetHeight + "px");
            if (mPill) mHost.style.setProperty("--nav-pill-h", mPill.offsetHeight + "px");
          }
          mRowH();
          if (document.fonts && document.fonts.ready) document.fonts.ready.then(mRowH);
          window.addEventListener("resize", mRowH, { passive: true });
          function mIsOpen() { return nav.classList.contains("is-open"); }
          function mOpen() {
            nav.classList.add("is-open");
            burger.setAttribute("aria-expanded", "true");
            mOpenY = window.scrollY;
          }
          function mClose() {
            if (!mIsOpen()) return;
            nav.classList.remove("is-open");
            burger.setAttribute("aria-expanded", "false");
            closeSubmenu();
            closeSearch();
          }
          closeMobileNav = mClose;
          burger.addEventListener("click", function (e) {
            e.stopPropagation();
            mOpen();
          });
          document.addEventListener("click", function (e) {
            if (mIsOpen() && !nav.contains(e.target)) mClose();
          });
          nav.addEventListener("click", function (e) {
            var a = e.target.closest("a");
            if (a && !a.hasAttribute("data-submenu-trigger")) mClose();
          });
          document.addEventListener("keydown", function (e) {
            if (e.key === "Escape") mClose();
          });
          window.addEventListener("scroll", function () {
            if (mIsOpen() && Math.abs(window.scrollY - mOpenY) > 40) mClose();
          }, { passive: true });
          var mdUp = window.matchMedia("(min-width: 768px)");
          if (mdUp.addEventListener) mdUp.addEventListener("change", function (e) { if (e.matches) mClose(); });
        }

        // ---- SERVICES disclosure (expanding drawer) ----
        // CSS handles the hover-open baseline (:has); JS adds the hover-intent close
        // delay, aria sync, keyboard, touch-open, Esc, outside-click, and aligns the
        // drawer items under SERVICES.
        var smItem = document.querySelector("[data-submenu-item]");
        var smTrigger = document.querySelector("[data-submenu-trigger]");
        var smDrawer = document.querySelector("[data-submenu-drawer]");

        if (nav && smItem && smTrigger && smDrawer) {
          var smSuppress = false;

          function smOffset() {
            var t = smTrigger.getBoundingClientRect();
            var d = smDrawer.getBoundingClientRect();
            // Add the trigger's left padding so items align with the SERVICES *text*,
            // not its (padded) box edge.
            var pad = parseFloat(getComputedStyle(smTrigger).paddingLeft) || 0;
            smDrawer.style.setProperty("--submenu-offset", Math.max(0, Math.round(t.left - d.left + pad)) + "px");
          }
          function smIsOpen() { return nav.classList.contains("is-submenu-open"); }
          function smOpen() {
            if (smSuppress) return;
            smOffset();
            nav.classList.add("is-submenu-open");
            smTrigger.setAttribute("aria-expanded", "true");
          }
          function smClose() {
            nav.classList.remove("is-submenu-open");
            smTrigger.setAttribute("aria-expanded", "false");
          }
          closeSubmenu = smClose;
          // No hover-open (user call, 23 Sep 2026: "click to view dropdown, not
          // the hover"): the pointer's hover no longer opens or holds the drawer;
          // the click below does, and the focus leaving it closes it.
          function smFocusOut(e) {
            var to = e.relatedTarget;
            if (!smItem.contains(to) && !smDrawer.contains(to)) smClose();
          }
          smItem.addEventListener("focusout", smFocusOut);
          smDrawer.addEventListener("focusout", smFocusOut);

          // ArrowDown drops focus into the drawer
          smTrigger.addEventListener("keydown", function (e) {
            if (e.key === "ArrowDown") {
              e.preventDefault();
              smOpen();
              var first = smDrawer.querySelector("a");
              if (first) first.focus();
            }
          });

          // A click TOGGLES the drawer, at every pointer (user call, 23 Sep 2026:
          // the trigger is a button, not a link, and "click to view dropdown, not
          // the hover").
          smTrigger.addEventListener("click", function (e) {
            e.preventDefault();
            if (smIsOpen()) smClose();
            else smOpen();
          });

          // Esc closes and returns focus to the trigger (without reopening)
          document.addEventListener("keydown", function (e) {
            if (e.key === "Escape" && smIsOpen()) {
              smClose();
              smSuppress = true;
              smTrigger.focus();
              window.setTimeout(function () { smSuppress = false; }, 120);
            }
          });

          // Click outside closes
          document.addEventListener("click", function (e) {
            if (smIsOpen() && !smItem.contains(e.target) && !smDrawer.contains(e.target)) smClose();
          });

          // Keep the drawer aligned under SERVICES whenever the row geometry changes.
          // The scroll-revealed home glyph (.show-home) expands BEFORE the links over
          // ~300ms, shifting SERVICES right; smOffset is otherwise only run on open.
          // A ResizeObserver on the ROW catches the glyph expand/collapse and web-font
          // reflow; a scroll re-sync (only while open) tracks the 300ms transition
          // smoothly. One rAF coalesces both into a single read + write per frame.
          var smRow = smTrigger.closest(".site-nav__row");
          var smRaf = 0;
          function smSyncOffset() {
            if (smRaf) return;
            smRaf = window.requestAnimationFrame(function () {
              smRaf = 0;
              smOffset();
            });
          }
          if (smRow && "ResizeObserver" in window) {
            // Observe ONLY the row: writing --submenu-offset resizes the drawer, not
            // the row, so this can never re-trigger the observer (no RO loop).
            var smRO = new ResizeObserver(function () { smSyncOffset(); });
            smRO.observe(smRow);
          }
          window.addEventListener("scroll", function () { if (smIsOpen()) smSyncOffset(); }, { passive: true });
          window.addEventListener("resize", smSyncOffset, { passive: true });
          smSyncOffset(); // warm --submenu-offset before the first interaction
        }

        // ---- Search flip (the pill rolls over to a search face) ----
        // CSS owns the 3D (site-header.css, "Search flip"); JS owns the open state,
        // the depth measurement, focus hand-over and the inert swap between faces.
        var sCube = document.querySelector("[data-search-cube]");
        var sFront = document.querySelector("[data-search-front]");
        var sFace = document.querySelector("[data-search-face]");
        var sOpenBtn = document.querySelector("[data-search-open]");
        var sCloseBtn = document.querySelector("[data-search-close]");
        var sInput = document.querySelector("[data-search-input]");

        if (nav && sCube && sFront && sFace && sOpenBtn && sInput) {
          function sIsOpen() { return nav.classList.contains("is-search-open"); }

          // Half the pill's REST height (row + padding, never the drawer) — the
          // distance both faces stand off the cube's centre. Measured, so a retune
          // of the label voice can't leave a face floating above or sunk below the
          // surface.
          function sDepth() {
            var row = sFront.querySelector(".site-nav__row");
            var cs = getComputedStyle(sFront);
            var h = (row ? row.offsetHeight : sFront.offsetHeight) +
              (parseFloat(cs.paddingTop) || 0) + (parseFloat(cs.paddingBottom) || 0);
            nav.style.setProperty("--nav-depth", (h / 2) + "px");
          }

          function sOpen() {
            if (sIsOpen()) return;
            closeSubmenu();
            sDepth();
            nav.classList.add("is-search-open");
            sOpenBtn.setAttribute("aria-expanded", "true");
            sFront.inert = true;
            sFace.inert = false;
            sInput.focus({ preventScroll: true });
          }

          function sClose(returnFocus) {
            if (!sIsOpen()) return;
            nav.classList.remove("is-search-open");
            sOpenBtn.setAttribute("aria-expanded", "false");
            sFace.inert = true;
            sFront.inert = false;
            if (returnFocus) sOpenBtn.focus({ preventScroll: true });
          }

          closeSearch = function () { sClose(false); };
          sFace.inert = true; // the search face starts edge-on: unreachable until opened
          sOpenBtn.addEventListener("click", sOpen);
          if (sCloseBtn) sCloseBtn.addEventListener("click", function () { sClose(true); });

          // An empty search just keeps the field.
          sFace.addEventListener("submit", function (e) {
            if (!sInput.value.trim()) {
              e.preventDefault();
              sInput.focus();
            }
          });

          // Esc rolls back to the nav; a click anywhere else rolls back quietly.
          document.addEventListener("keydown", function (e) {
            if (e.key === "Escape" && sIsOpen()) sClose(true);
          });
          document.addEventListener("click", function (e) {
            if (sIsOpen() && !sCube.contains(e.target)) sClose(false);
          });
          window.addEventListener("resize", function () { if (sIsOpen()) sDepth(); }, { passive: true });
        }
      })();

    },
  };
})(Drupal, once);
