/* reveal.js — GENERATED by scripts/theme-js.mjs from the repo-root js/reveal.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconReveal.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconReveal = {
    attach(context) {
      if (!once("reveal", "html", context).length) return;

      /* reveal.js — generic scroll-reveal: adds .is-visible to [data-animate] elements
       * as they scroll into view, driving the opacity+rise host in
       * src/utilities/animations.css. The CSS owns the transition (and the
       * --animate-delay stagger); this only toggles the class once per element.
       *
       * No-JS safe: without .js-animations the host renders elements fully visible.
       * Reduced-motion safe: the CSS host already resets [data-animate] to visible
       * with no transition under prefers-reduced-motion, so toggling the class is inert.
       *
       * This is the missing companion to js/work.js — work.js only drives [data-reveal]
       * swipes, .section-title underlines, and .project-card hover-video; nothing else
       * revealed [data-animate]. Used by the /work and /work/article page chrome.
       * Also home here: the word cascade ([data-reveal-words]), the media reveals
       * ([data-reveal-img]) and the hairline draws ([data-rule]).
       * Drupal: Drupal.behaviors.iconReveal. */
      (function () {
        "use strict";

        // Three independent sections — fade-ups, media reveals, hairlines — each
        // guarded on its OWN markup. No early return: a page with no [data-animate]
        // (the bare Drupal front page) still has rules to draw (LESSONS.md).
        var nodes = Array.prototype.slice.call(document.querySelectorAll("[data-animate]"));
        if (nodes.length) {
          // No IntersectionObserver → reveal everything immediately (no-JS equivalent).
          if (!("IntersectionObserver" in window)) {
            nodes.forEach(function (el) { el.classList.add("is-visible"); });
          } else {
            var io = new IntersectionObserver(function (entries) {
              entries.forEach(function (e) {
                if (!e.isIntersecting) return;
                e.target.classList.add("is-visible");
                io.unobserve(e.target);
              });
            }, { threshold: 0.1, rootMargin: "0px 0px -50px 0px" });

            nodes.forEach(function (el) { io.observe(el); });
          }
        }

        /* ---- Word-cascade text reveals ([data-reveal-words]) ---------------------
         * Each word is wrapped in a mask (.sw > .sw__i) indexed with --w; the CSS
         * (utilities/animations.css) staggers the rise on .is-revealed. The
         * splitter walks TEXT NODES only, so inline elements (links) survive intact
         * — their words are masked inside them. Plain-text elements get the
         * SplitText-style aria shim (aria-label + hidden words); elements
         * containing links must NOT (it would hide the links from AT), so there the
         * split spans simply read in document order. Skipped under reduced motion
         * (text is left exactly as authored). Lifted here from js/home-c.js (3c)
         * when the page H1s took the cascade — the intro's gesture, on every
         * masthead and article title (Sep 2026). */
        var reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
        var wordEls = Array.prototype.slice.call(document.querySelectorAll("[data-reveal-words]"));
        if (wordEls.length && !reduce) {
          wordEls.forEach(function (el) {
            var hasLinks = !!el.querySelector("a");
            if (!hasLinks) {
              // Respect an authored aria-label (e.g. "More work" on a link whose
              // visible text is just "More") — only shim one from the text when
              // the markup didn't provide its own.
              if (!el.hasAttribute("aria-label")) {
                el.setAttribute("aria-label", el.textContent.replace(/\s+/g, " ").trim());
              }
            }
            var idx = 0;
            var walk = function (node) {
              if (node.nodeType === 3) {
                var frag = document.createDocumentFragment();
                node.textContent.split(/(\s+)/).forEach(function (part) {
                  if (!part) return;
                  if (!part.trim()) { frag.appendChild(document.createTextNode(" ")); return; }
                  var w = document.createElement("span");
                  w.className = "sw";
                  if (!hasLinks) w.setAttribute("aria-hidden", "true");
                  var wi = document.createElement("span");
                  wi.className = "sw__i";
                  wi.textContent = part;
                  wi.style.setProperty("--w", idx++);
                  w.appendChild(wi);
                  frag.appendChild(w);
                });
                node.parentNode.replaceChild(frag, node);
              } else if (node.nodeType === 1) {
                Array.prototype.slice.call(node.childNodes).forEach(walk);
              }
            };
            Array.prototype.slice.call(el.childNodes).forEach(walk);
          });
          if (!("IntersectionObserver" in window)) {
            wordEls.forEach(function (el) { el.classList.add("is-revealed"); });
          } else {
            var wIO = new IntersectionObserver(function (entries) {
              entries.forEach(function (e) {
                if (!e.isIntersecting) return;
                e.target.classList.add("is-revealed");
                wIO.unobserve(e.target);
              });
            }, { threshold: 0.2, rootMargin: "0px 0px -8% 0px" });
            wordEls.forEach(function (el) { wIO.observe(el); });
          }
        }

        /* ---- rules draw themselves in --------------------------------------------
         * Every hairline on the site ([data-rule], and the clients marquee's
         * pseudo-element pair via [data-rule-host]) grows from its left edge as it
         * arrives. One observer for the lot so the whole page draws at one speed and
         * nothing has to remember to opt in beyond the attribute.
         *
         * Latched, not toggled: a rule is a structural line between two pieces of
         * content, and re-drawing it every time it re-enters would make the page
         * feel like it was still loading. Unobserved once drawn.
         */
        /* Media clip + scale reveals — the shared .media-reveal primitive
         * ([data-reveal-img] frames whose media opens up-and-right on scroll-in;
         * styles in utilities/home-c.css). Lifted here at its THIRD consumer:
         * js/home-c.js and js/news.js each carried this identical observer for
         * their own page, and the news article template made it three — this file
         * is where every page's scroll-reveals already live. Same thresholds the
         * copies used. Latched, like everything here. */
        var figEls = Array.prototype.slice.call(document.querySelectorAll("[data-reveal-img]"));
        if (figEls.length) {
          if (!("IntersectionObserver" in window)) {
            figEls.forEach(function (el) { el.classList.add("is-revealed"); });
          } else {
            var figIO = new IntersectionObserver(function (entries) {
              entries.forEach(function (e) {
                if (!e.isIntersecting) return;
                e.target.classList.add("is-revealed");
                figIO.unobserve(e.target);
              });
            }, { threshold: 0.18, rootMargin: "0px 0px -8% 0px" });
            figEls.forEach(function (el) { figIO.observe(el); });
          }
        }

        var ruleEls = Array.prototype.slice.call(
          document.querySelectorAll("[data-rule], [data-rule-host]")
        );
        if (ruleEls.length) {
          if (!("IntersectionObserver" in window)) {
            ruleEls.forEach(function (el) { el.classList.add("is-drawn"); });
          } else {
            var ruleIO = new IntersectionObserver(
              function (entries) {
                entries.forEach(function (e) {
                  if (!e.isIntersecting) return;
                  e.target.classList.add("is-drawn");
                  ruleIO.unobserve(e.target);
                });
              },
              // a sliver is enough: these are 1px lines, so waiting for a ratio of
              // them would never fire
              { rootMargin: "0px 0px -5% 0px" }
            );
            ruleEls.forEach(function (el) { ruleIO.observe(el); });
          }
        }
      })();

    },
  };
})(Drupal, once);
