/* site-footer.js — GENERATED by scripts/theme-js.mjs from the repo-root js/site-footer.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconFooter.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconFooter = {
    attach(context) {
      if (!once("site-footer", "html", context).length) return;

      /* site-footer.js — the global footer's motion. One IIFE, two concerns:
       *
       * 1. REVEAL — toggles .is-revealed as the panel enters and leaves the
       *    viewport, so the footer replays every time you come back to it rather
       *    than firing once for the life of the page. CSS owns the staggered
       *    fade-up, the LET'S TALK word rise and the logo's swivel.
       *    Without JS (or without IntersectionObserver) the footer is simply
       *    visible: the hidden state lives behind .js-animations, exactly as
       *    reveal.css and tagline.css do it.
       *
       * 2. THE FILMS IN THE MARK — cross-fades the hero's banner videos behind the
       *    logo's mask. Videos are the expensive part of this footer, so exactly one
       *    decodes at a time and only while the panel is on screen; they ship
       *    preload="none", which means nothing is even fetched until the first
       *    play() here. A backgrounded tab stops them too.
       *
       * 3. SCROLL-VELOCITY SKEW — samples scroll speed and writes ONE custom
       *    property, --footer-skew, on the footer per frame; the blocks inside
       *    shear by it (the lockup harder than the rest). Velocity is not
       *    expressible as a CSS scroll timeline — those are position-driven — so
       *    this is the one part that must be scripted.
       *
       * Why its own file rather than a section of home-c.js: the footer is global
       * and ships on pages that never load the homepage bundle (and have no GSAP),
       * so its behaviour has to travel with it. The velocity sampler this file
       * once carried was deliberately the same shape as news.js's — and when the
       * /work landing arrived as the third consumer, it was lifted into the shared
       * js/velocity-lean.js exactly as this note used to promise. The skew is now
       * one call in section 3.
       *
       * Drupal: Drupal.behaviors.iconFooter, attached via the `icon/site-footer`
       * library alongside the footer region template.
       */
      (function () {
        "use strict";

        var footer = document.querySelector(".site-footer");
        if (!footer) return;

        var reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

        /* ---- 1. reveal, every time -------------------------------------------- */

        if (reduce || !("IntersectionObserver" in window)) {
          footer.classList.add("is-revealed");
        } else {
          // Deliberately NOT unobserved after the first hit: the class tracks
          // whether the panel is on screen, so leaving and coming back replays the
          // whole reveal.
          //
          // Two observers, with two different boundaries, on purpose. Arming is
          // generous — a sliver of the panel is enough, since it is taller than most
          // viewports and waiting for a percentage of it would fire late or never.
          // Disarming waits until the panel is a further 40% of the viewport clear.
          // Because the disarm boundary sits strictly outside the arm boundary, a
          // scroll that rests on the threshold cannot flicker the footer on and off;
          // with one shared boundary a single pixel of jitter would re-trigger
          // everything.
          new IntersectionObserver(
            function (entries) {
              if (entries[0].isIntersecting) footer.classList.add("is-revealed");
            },
            { rootMargin: "0px 0px -10% 0px" }
          ).observe(footer);

          new IntersectionObserver(
            function (entries) {
              if (!entries[0].isIntersecting) footer.classList.remove("is-revealed");
            },
            { rootMargin: "40% 0px 40% 0px" }
          ).observe(footer);
        }

        /* ---- 2. the films in the mark ------------------------------------------ */

        (function () {
          var stage = footer.querySelector(".site-footer__logo");
          if (!stage) return;
          var slides = [].slice.call(stage.querySelectorAll(".site-footer__slide"));
          if (!slides.length) return;

          // The hero's own video hold (js/home-c.js: HOLD_VIDEO), so the same
          // footage keeps the same pace in both places. A setTimeout chain rather
          // than setInterval, also as the hero does it — a slide that stalls should
          // delay the next one, not have it fire underneath.
          var HOLD = 6000;
          var i = 0, timer = 0, live = false;

          function show(el) {
            el.classList.add("is-current");
            try { el.currentTime = 0; } catch (e) {} // start clean, not mid-loop
            if (reduce) return; // reduced motion holds a first frame
            var p = el.play();
            if (p && p.catch) p.catch(function () {}); // autoplay policy: ignore
          }

          function step() {
            var prev = slides[i];
            i = (i + 1) % slides.length;
            prev.classList.remove("is-current");
            prev.pause();
            show(slides[i]);
            timer = setTimeout(step, HOLD);
          }

          function start() {
            if (live) return;
            live = true;
            show(slides[i]);
            if (!reduce && slides.length > 1) timer = setTimeout(step, HOLD);
          }

          function stop() {
            live = false;
            clearTimeout(timer);
            timer = 0;
            slides.forEach(function (v) { v.pause(); });
          }

          if ("IntersectionObserver" in window) {
            new IntersectionObserver(function (entries) {
              entries[0].isIntersecting ? start() : stop();
            }, { rootMargin: "10% 0px" }).observe(stage);
          } else {
            start();
          }

          document.addEventListener("visibilitychange", function () {
            if (document.hidden) stop();
          });
        })();

        /* ---- 3. scroll-velocity skew ------------------------------------------- */

        if (reduce) return;

        // The shared engine (js/velocity-lean.js — lifted from here at its third
        // consumer, as this file's header promised). MAX 1.8deg: past ~2 the shear
        // stops reading as motion and starts reading as a broken layout, and the
        // lockup multiplies it.
        if (window.ICON && window.ICON.velocityLean) {
          window.ICON.velocityLean(footer, footer, "--footer-skew", 1.8);
        }
      })();

    },
  };
})(Drupal, once);
