/* strip-drift.js — GENERATED by scripts/theme-js.mjs from the repo-root js/strip-drift.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * Plain IIFE (no behaviour wrapper) — see the generator for why. */

/* strip-drift.js — THE marquee engine, shared: an endless drift that a hand
 * can take hold of. Samples one position for a strip — drifting at the
 * site's one strip speed, moved 1:1 by a pointer drag, carrying the drag's
 * release velocity into a decaying momentum, and RE-POINTED by a fling
 * (velocity for a real throw, net displacement for a slow carry, a tap
 * changes nothing) — and hands it to the consumer every frame to render
 * as it likes.
 *
 * Lifted at the THIRD consumer, as docs/animation.md rule 4 has it: the
 * gallery scroller (js/work-scroller.js), the filmstrip (js/filmstrip.js)
 * and the clients logo marquee (js/clients-marquee.js) carried the same
 * integrator and the same drag, byte for byte; what differs is what each
 * draws from the number — one track wrapping, a lean, two rows reading one
 * phase with opposite signs — and that stays with each.
 *
 *   var drift = window.ICON.stripDrift({
 *     reduce: bool,             // no drift and no momentum
 *     render: function (state, dt) { … },   // every frame, after the step
 *     onDragStart: function (el) {},        // optional
 *     onDragEnd: function (el, tapped) {},  // optional
 *     onTap: function (target, el) {},      // optional: a press under the slop
 *   });
 *   drift.attach(viewport, polarity);  // a drag on this element moves the
 *                                       // position by ±1 (the marquee's
 *                                       // reversed row reads it negated)
 *   drift.state — { pos, vel, dir, dragging, dragVel, hold }; a consumer
 *   may write pos (a glide) and hold (pause the drift while it does).
 *
 * A tiny namespaced global, like js/velocity-lean.js and js/cursor-tilt.js:
 * consumers load AFTER this one and soft-guard on its presence.
 * Drupal: its own `icon/strip-drift` library; consumer behaviours declare
 * the dependency. */
(function () {
  "use strict";

  window.ICON = window.ICON || {};

  var SPEED = 55;       // px/s — the shared strip speed
  var MAX_FLING = 2200; // px/s a release can hand over
  var TAP_SLOP = 6;     // px of movement that still counts as a tap

  window.ICON.stripDrift = function (opts) {
    var reduce = !!opts.reduce;
    var state = { pos: 0, vel: 0, dir: 1, dragging: false, dragVel: 0, hold: false, moved: 0 };
    var active = null;   // the element under the hand, if any

    var last = performance.now();
    var tick = function (now) {
      var dt = Math.min(0.05, (now - last) / 1000);
      last = now;
      if (!state.dragging && !state.hold) {
        var auto = reduce ? 0 : SPEED * state.dir;
        state.pos += (auto + state.vel) * dt;
        state.vel *= Math.pow(0.9, dt * 60); // exponential decay, frame-rate independent
        if (Math.abs(state.vel) < 1) state.vel = 0;
      }
      opts.render(state, dt, now);
      requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);

    var attach = function (el, polarity) {
      var sign = polarity === -1 ? -1 : 1;
      var startX = 0, startPos = 0, lastX = 0, lastT = 0, downTarget = null;
      el.addEventListener("pointerdown", function (e) {
        active = el;
        state.dragging = true;
        state.moved = 0;
        state.dragVel = 0;
        state.vel = 0;
        downTarget = e.target;
        startX = lastX = e.clientX;
        startPos = state.pos;
        lastT = performance.now();
        el.classList.add("is-dragging");
        if (opts.onDragStart) opts.onDragStart(el);
        try { el.setPointerCapture(e.pointerId); } catch (err) {}
      });
      el.addEventListener("pointermove", function (e) {
        if (active !== el) return;
        var now = performance.now();
        var dx = e.clientX - lastX;
        state.moved += Math.abs(dx);
        state.pos = startPos - sign * (e.clientX - startX);
        if (now - lastT > 0) state.dragVel = (-sign * dx) / ((now - lastT) / 1000);
        lastX = e.clientX;
        lastT = now;
      });
      var endDrag = function (e) {
        if (active !== el) return;
        active = null;
        state.dragging = false;
        el.classList.remove("is-dragging");
        var tapped = state.moved <= TAP_SLOP && !!e && e.type === "pointerup";
        if (opts.onDragEnd) opts.onDragEnd(el, tapped);
        if (tapped) {
          if (opts.onTap) opts.onTap(downTarget, el);
        }
        else {
          state.vel = reduce ? 0 : Math.max(-MAX_FLING, Math.min(MAX_FLING, state.dragVel));
          // THE DRIFT FOLLOWS THE DRAG: velocity decides it for a real
          // fling, net displacement for a slow carry
          if (Math.abs(state.vel) > 40) state.dir = state.vel > 0 ? 1 : -1;
          else if (Math.abs(state.pos - startPos) > TAP_SLOP) state.dir = state.pos > startPos ? 1 : -1;
        }
        state.dragVel = 0;
        downTarget = null;
      };
      el.addEventListener("pointerup", endDrag);
      el.addEventListener("pointercancel", endDrag);
      // a lost capture (tab switch, gesture stolen mid-drag) must not leave
      // the strip stuck in the dragging state
      el.addEventListener("lostpointercapture", endDrag);
      // images must not start a native drag mid-gesture (Firefox ghosts)
      el.addEventListener("dragstart", function (e) { e.preventDefault(); });
      // a real drag must not land as a click on whatever is under the hand
      el.addEventListener("click", function (e) {
        if (state.moved > TAP_SLOP) { e.preventDefault(); e.stopPropagation(); }
      }, true);
    };

    return { state: state, attach: attach };
  };
})();
