/* subscribe-reveal.js — GENERATED by scripts/theme-js.mjs from the repo-root js/subscribe-reveal.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconSubscribeReveal.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconSubscribeReveal = {
    attach(context) {
      if (!once("subscribe-reveal", "html", context).length) return;

      /* subscribe-reveal.js — the header-B Subscribe disclosure. The masthead's
       * Subscribe swaps for the email form on click (user call): the field is
       * FOCUSED and typable immediately, and the whole thing collapses back to
       * the lone button on click-away, focus leaving the slot, or Escape (which
       * also returns focus to the trigger). The animation is pure CSS — this
       * file only swaps .is-open and keeps the hidden half `inert`, because a
       * collapsed 0fr/overflow-hidden box is invisible but still TABBABLE
       * without it.
       *
       * The revealed Subscribe stays the shared inert [data-subscribe] hook —
       * submitting ships with the newsletter slice, same as the footer.
       *
       * Drupal: Drupal.behaviors.iconSubscribeReveal via `icon/subscribe-reveal`. */
      (function () {
        "use strict";

        var slot = document.querySelector("[data-subscribe-slot]");
        if (!slot) return;
        var trigger = slot.querySelector("[data-subscribe-open]");
        var closed = slot.querySelector(".page-header__subscribe-closed");
        var reveal = slot.querySelector(".page-header__subscribe-reveal");
        var input = slot.querySelector(".page-header__email");
        if (!trigger || !closed || !reveal || !input) return;

        reveal.setAttribute("inert", "");

        var open = function () {
          slot.classList.add("is-open");
          trigger.setAttribute("aria-expanded", "true");
          reveal.removeAttribute("inert");
          closed.setAttribute("inert", "");
          // typable at once, mid-animation; preventScroll — the field is already
          // in view and a focus jump would fight the height ease
          input.focus({ preventScroll: true });
        };

        var close = function (refocus) {
          if (!slot.classList.contains("is-open")) return;
          slot.classList.remove("is-open");
          trigger.setAttribute("aria-expanded", "false");
          reveal.setAttribute("inert", "");
          closed.removeAttribute("inert");
          if (refocus) trigger.focus({ preventScroll: true });
        };

        trigger.addEventListener("click", open);

        // pointerdown, not click: a click that starts a drag outside still closes,
        // and closing before the other element's click means no double-handling
        document.addEventListener("pointerdown", function (e) {
          if (!slot.contains(e.target)) close(false);
        });

        slot.addEventListener("focusout", function (e) {
          // relatedTarget is null when focus leaves the document — treat as away
          if (!e.relatedTarget || !slot.contains(e.relatedTarget)) close(false);
        });

        document.addEventListener("keydown", function (e) {
          if (e.key === "Escape") close(true);
        });
      })();

    },
  };
})(Drupal, once);
