/* subscribe-reveal.js — GENERATED by scripts/theme-js.mjs from the repo-root js/subscribe-reveal.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconSubscribeReveal.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconSubscribeReveal = {
    attach(context) {
      if (!once("subscribe-reveal", "html", context).length) return;

      /* subscribe-reveal.js — the masthead Subscribe bar's hint swap (the pill that
       * is the header search face's twin; page-header.css "the Subscribe bar").
       * Three states live in the one field: at rest its hint reads "Subscribe";
       * while the pointer is over the bar or the field has focus the hint is
       * "Your email"; typed, the address shows in the field's own face. The hints
       * come from the markup (data-hint-rest / data-hint-hover) so Drupal's |t
       * owns the words. Esc empties the field and lets it go.
       *
       * Submitting stays the shared inert [data-subscribe] hook — it ships with
       * the newsletter slice, same as the footer.
       *
       * Drupal: Drupal.behaviors.iconSubscribeReveal via `icon/subscribe-reveal`. */
      (function () {
        "use strict";

        var bars = document.querySelectorAll("[data-subscribe-bar]");
        Array.prototype.forEach.call(bars, function (bar) {
          var input = bar.querySelector("[data-subscribe-input]");
          if (!input) return;
          var rest = input.getAttribute("data-hint-rest") || input.placeholder;
          var hover = input.getAttribute("data-hint-hover") || rest;
          var over = false;

          function sync() {
            var active = over || document.activeElement === input;
            input.placeholder = active ? hover : rest;
            bar.classList.toggle("is-hinting", active);
          }

          bar.addEventListener("pointerenter", function () { over = true; sync(); });
          bar.addEventListener("pointerleave", function () { over = false; sync(); });
          input.addEventListener("focus", sync);
          input.addEventListener("blur", sync);
          input.addEventListener("keydown", function (e) {
            if (e.key === "Escape") {
              input.value = "";
              input.blur();
            }
          });
        });
      })();

    },
  };
})(Drupal, once);
