/* testimonials.js — GENERATED by scripts/theme-js.mjs from the repo-root js/testimonials.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconTestimonials.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconTestimonials = {
    attach(context) {
      if (!once("testimonials", "html", context).length) return;

      /* testimonials.js — the quotes carousel (components/testimonials.css): one
       * quote showing at a time, the arrows stepping through them with wrap, the
       * counter reading "01 / 06", the arrow keys stepping too while the focus is
       * inside. The quotes are counted, not the children: in the Canvas editor an
       * empty slot holds a placeholder child (the Filmstrip's lesson). One quote
       * → data-count="1", and the CSS takes the bar away. In the editor's frame
       * every quote shows, stacked (.is-editing), to select and reorder. */
      (function () {
        "use strict";
        var reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
        function pad(n) { return (n < 10 ? "0" : "") + n; }

        document.querySelectorAll("[data-testimonials]").forEach(function (section) {
          // The quotes wherever they sit in the track: a Testimonial (item) block
          // renders inside Drupal's block wrapper, so they are not the track's
          // own children (user catch, Sep 2026: one quote, the bar still there).
          var track = section.querySelector(".testimonials__track");
          var items = Array.prototype.slice.call(track ? track.querySelectorAll(".testimonial") : []);
          var count = items.length;
          section.setAttribute("data-count", String(count));
          var frame = window.frameElement;
          if (frame && frame.hasAttribute("data-canvas-preview")) {
            section.classList.add("is-editing");
            return;
          }
          if (!count) return;

          var indexEl = section.querySelector("[data-testimonials-index]");
          var countEl = section.querySelector("[data-testimonials-count]");
          var prev = section.querySelector("[data-testimonials-prev]");
          var next = section.querySelector("[data-testimonials-next]");
          if (countEl) countEl.textContent = pad(count);
          var current = 0;

          function show(i, animate) {
            current = (i + count) % count;
            items.forEach(function (item, k) {
              var on = k === current;
              item.setAttribute("aria-hidden", on ? "false" : "true");
              if (on) item.removeAttribute("inert"); else item.setAttribute("inert", "");
              item.classList.remove("is-showing");
              if (on && animate && !reduce) {
                // restart the entrance
                void item.offsetWidth;
                item.classList.add("is-showing");
              }
            });
            if (indexEl) indexEl.textContent = pad(current + 1);
          }
          show(0, false);
          if (count === 1) return;

          if (prev) prev.addEventListener("click", function () { show(current - 1, true); });
          if (next) next.addEventListener("click", function () { show(current + 1, true); });
          section.addEventListener("keydown", function (e) {
            if (e.target.closest && e.target.closest("input, textarea, select")) return;
            if (e.key === "ArrowLeft") { e.preventDefault(); show(current - 1, true); }
            if (e.key === "ArrowRight") { e.preventDefault(); show(current + 1, true); }
          });
        });
      })();

    },
  };
})(Drupal, once);
