/* velocity-lean.js — GENERATED by scripts/theme-js.mjs from the repo-root js/velocity-lean.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * Plain IIFE (no behaviour wrapper) — see the generator for why. */

/* velocity-lean.js — THE scroll-velocity engine, shared. Samples scroll
 * speed, decays it once the scroll events stop (nothing else would zero
 * it), lerps toward a clamped angle and writes ONE custom property per
 * frame; an IntersectionObserver idles the whole thing while the section
 * is off screen, and the rAF loop only runs while there is motion left to
 * settle.
 *
 * Lifted at the THIRD consumer — the moment docs/animation.md rule 4 and
 * site-footer.js's own header named in advance: the footer's skew
 * (--footer-skew), the /news rows' and the /work landing's leans were three
 * byte-identical engines differing only in host, property name and cap.
 *
 * All three are SKEWS now (--footer-skew, --nl-skew, --wl-skew): the cards'
 * velocity rotation became a skewY in Aug 2026, matching the GreenSock
 * skew-on-scroll gesture the homepage drives through GSAP. The engine itself
 * never cared — it samples a velocity and writes an angle; what consumes that
 * angle is the consumer's business. The file name is historical.
 *
 * A tiny namespaced global rather than a module — the project is vanilla
 * one-IIFE-per-behaviour files; consumers simply load AFTER this one and
 * soft-guard on its presence. Reduced-motion guarding stays with the
 * CALLER: it owns the decision that motion exists at all.
 *
 * Drupal: its own `icon/velocity-lean` library; consumer behaviours
 * (iconFooter, iconNews, iconWorkLanding) declare the dependency. */
(function () {
  "use strict";

  window.ICON = window.ICON || {};

  // observeEl: the section whose visibility gates the work; writeEl: where
  // the property lands (consumers inherit it from there); prop: the custom
  // property name; max: the angle cap in degrees.
  window.ICON.velocityLean = function (observeEl, writeEl, prop, max) {
    var VEL_AT_MAX = 2600; // scroll px/s that reaches the full angle
    var clamp = function (v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; };

    var inView = !("IntersectionObserver" in window);
    if (!inView) {
      new IntersectionObserver(function (entries) {
        inView = entries[0].isIntersecting;
      }, { rootMargin: "20% 0px" }).observe(observeEl);
    }

    var lastY = window.scrollY, lastT = performance.now();
    var vel = 0, cur = 0, raf = 0, prevT = 0;

    var tick = function (now) {
      raf = 0;
      var dt = Math.min(0.05, (now - (prevT || now)) / 1000);
      prevT = now;
      vel *= Math.pow(0.86, dt * 60);
      if (Math.abs(vel) < 20) vel = 0;
      var target = inView ? clamp((vel / VEL_AT_MAX) * max, -max, max) : 0;
      cur += (target - cur) * Math.min(1, dt * 7);
      if (Math.abs(cur) < 0.01 && !vel) cur = 0;
      writeEl.style.setProperty(prop, cur.toFixed(3) + "deg");
      if (vel || Math.abs(cur) > 0.005) raf = requestAnimationFrame(tick);
      else prevT = 0; // settled — the loop stops until the next scroll
    };

    window.addEventListener("scroll", function () {
      var now = performance.now();
      var dt = (now - lastT) / 1000;
      if (dt > 0) vel = clamp((window.scrollY - lastY) / dt, -12000, 12000);
      lastY = window.scrollY;
      lastT = now;
      if (!raf) raf = requestAnimationFrame(tick);
    }, { passive: true });
  };
})();
