/* work-video.js — GENERATED by scripts/theme-js.mjs from the repo-root js/work-video.js.
 * Do not edit here: edit the source and run `npm run build:theme`.
 * The source IIFE runs once per page inside Drupal.behaviors.iconWorkVideo.attach()
 * (once() on <html>), so the behaviour body is byte-identical to the prototype's. */
((Drupal, once) => {
  Drupal.behaviors.iconWorkVideo = {
    attach(context) {
      if (!once("work-video", "html", context).length) return;

      /* work-video.js — click-to-play film (born on The Athlete's Foot example,
       * Sep 2026). The cover art and the play control both start the film: reveal
       * the native controls, play, fade the art frame. No autoplay on purpose —
       * this is the SOUND-ON cut, so it waits for the gesture (which also
       * satisfies every mobile autoplay policy for free).
       * Drupal: Drupal.behaviors.iconWorkVideo over [data-work-video]. */
      (function () {
        var roots = document.querySelectorAll("[data-work-video]");
        roots.forEach(function (root) {
          var video = root.querySelector(".work-video__media");
          if (!video) return;
          var start = function () {
            root.classList.add("is-playing");
            video.setAttribute("controls", "");
            var p = video.play();
            if (p && p.catch) p.catch(function () {});
          };
          root.querySelectorAll("[data-work-video-start]").forEach(function (el) {
            el.addEventListener("click", start, { once: true });
          });
        });
      })();

    },
  };
})(Drupal, once);
